### ISSUE TITLE
last() returns null if no element available

### ISSUE THREAD

**Issue by mwenell** [Zenoo/LightQuery#5]
**Describe the bug**
If you search the last element of something with .last() and want to get the text() content of this item, it gives error because .last() returns null and .text() does not exist in null.

**To Reproduce**

1. Open any page
2. Add LightQuery there
3. The following is runned on Chrome browser empty page:

$('body')
_$ [body]
$('body').last().text()
'\n    \n    \n    \n    \n    \n    \n  \n\n'
$('body .not-existing-class').last()
null
$('body .not-existing-class').last().text()
VM570:1 Uncaught TypeError: Cannot read properties of null (reading 'text')
    at <anonymous>:1:37
(see error above)

**Expected behavior**
.last() should return empty list as same way others are doing when no element finded. And a text() function after it in chain should return empty string, not error.

**Desktop (please complete the following information):**
 - OS: MAC 14.2.1 (23C71)
 - Browser Chrome
 - Version 120.0.6099.129 (Official Build) (x86_64)

**Comment by Zenoo** [comment]
I didn't realize this project was being used by someone !

Thanks for noticing, this should be fixed in v1.2.6

**Comment by mwenell** [comment]
Hi,

this is a good project but for special uses as i do. I use it in Chrome extension where is a limited size for my code. This extension runs my code on every web page.

The same issue might be in .first() as well.

HOWEVER, the :first and :last does selectors do not work either, maybe same problem.

**Comment by Zenoo** [comment]
The fix I deployed should fix the issue for both `.first()` and `.last()`.

As for the `:first` and `:last` selectors, they are not valid CSS selectors, you should use `:first-child`, `:first-of-type`, `:last-child`, `:last-of-type` instead, depending on your needs.

**Comment by mwenell** [comment]
Hie,

Thanks.

By the way, Chat GPT recommended your library when i was asking smaller jQuery library.

- Mika

**Comment by Zenoo** [comment]
That's ... surprising to say the least, thanks for the heads up !
